### ISSUE TITLE
google_fonts was unable to load font Poppins-Regular

### ISSUE THREAD

**Issue by CmoZeghen** [material-foundation/flutter-packages#441]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
I have this error every time I launch my flutter application, I don't understand the cause.

Failed to load font with url https://fonts.gstatic.com/s/a/705290b12f58c6d70aafcaaf461dbc3d2f7f19d0f4362af1843b107d95d4960a.ttf: ClientException with SocketException: Failed host lookup: 'fonts.gstatic.com' (OS Error: nodename nor servname provided, or not known, errno = 8), uri=https://fonts.gstatic.com/s/a/705290b12f58c6d70aafcaaf461dbc3d2f7f19d0f4362af1843b107d95d4960a.ttf

## Steps to reproduce:
1.
1.
1.

### Relevant log output

```shell
[!] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale en-GB)
    • Flutter version 3.10.6 on channel stable at /Users/graphics01/fvm/versions/3.10.6
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/graphics01/fvm/versions/3.10.6. Consider adding /Users/graphics01/fvm/versions/3.10.6/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/graphics01/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/graphics01/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/graphics01/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Users/graphics01/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.68.0

[✓] VS Code (version 1.79.0)
    • VS Code at /Users/graphics01/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • Cto’s iPhone (mobile) • 00008020-001015A43430003A • ios            • iOS 16.5.1 20F75
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 113.0.5672.63

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by guidezpl** [comment]
Well the file is available for download, so it must be the application doesn't have access to the internet.. Did you follow the troubleshooting steps in the log output?

**Comment by DavidOrakpo** [comment]
I'm also having this issue

**Comment by madaomaraly2010** [comment]
I'm also having this issue

**Comment by guidezpl** [comment]
Closing in favor of https://github.com/material-foundation/flutter-packages/issues/560

**Comment by caseyryan** [comment]
The issue reproduces again. The thread mentioned above doesn't exist. 
``` 
I/flutter (24726): Error: google_fonts was unable to load font Righteous-Regular because the following exception occurred:
I/flutter (24726): Unable to load asset: "AssetManifest.json".
I/flutter (24726): The asset does not exist or has empty data.
I/flutter (24726): See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.
I/flutter (24726): If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
E/flutter (24726): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Unable to load asset: "AssetManifest.json".
E/flutter (24726): The asset does not exist or has empty data.
E/flutter (24726): #0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:332:13)
asset_bundle.dart:332
E/flutter (24726): <asynchronous suspension>
E/flutter (24726): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:92:27)
asset_bundle.dart:92
E/flutter (24726): <asynchronous suspension>
E/flutter (24726): #2      AssetManifest._loadAssetManifestJson (package:google_fonts/src/asset_manifest.dart:34:26)
asset_manifest.dart:34
E/flutter (24726): <asynchronous suspension>
E/flutter (24726): #3      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:150:31)
google_fonts_base.dart:150
E/flutter (24726): <asynchronous suspension>
E/flutter (24726): #4      googleFontsTextStyle.<anonymous closure> (package:google_fonts/src/google_fonts_base.dart:115:22)
google_fonts_base.dart:115
E/flutter (24726): <asynchronous suspension> ```

It appeared after I updated Flutter from 3.29.2 to 3.38.5 . Before this, it worked. It's not a network issue of some invalid caches, I checked that. The same issue reproducec on my collegue's environment as well
