### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by claudneysessa** [material-foundation/flutter-packages#521]
### Package

All packages

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:

When creating a new project and adding the package it shows the error:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

## Steps to reproduce:

Just create a new project, add the package and build it

When removing the package the error disappears!

### Relevant log output

```shell
D/EGL_emulation( 8270): eglMakeCurrent: 0x7b4b934de0: ver 3 0 (tinfo 0x7b4b797560)
E/flutter ( 8270): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 8270): #0      PathProviderApi.getApplicationSupportPath (package:path_provider_android/messages.g.dart:65:7)
E/flutter ( 8270): <asynchronous suspension>
E/flutter ( 8270): #1      getApplicationSupportDirectory (package:path_provider/path_provider.dart:78:24)
E/flutter ( 8270): <asynchronous suspension>
E/flutter ( 8270): #2      _localPath (package:google_fonts/src/file_io_desktop_and_mobile.dart:39:21)
E/flutter ( 8270): <asynchronous suspension>
```

**Comment by guidezpl** [comment]
I can't repro this, could you please share more details (package version, device, OS version, etc.)?
