### ISSUE TITLE
Font loading issue.

### ISSUE THREAD

**Issue by vernalclareai** [material-foundation/flutter-packages#588]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

### Relevant log output

```shell
flutter: If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to load font with url https://fonts.gstatic.com/s/a/8fba6fe30d0e768cf6ec5468e843b4834a29bf71133ca031a80e45d464472beb.ttf: Connection reset by peer
#0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:256:5)
<asynchronous suspension>
#1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:173:11)
<asynchronous suspension>
flutter: Error: google_fonts was unable to load font Inter-ExtraBold because the following exception occurred:
Exception: Failed to load font with url https://fonts.gstatic.com/s/a/d1adf80c80c93bbc514bb2899b3f84e2ff256004e9ad48bc405b568dc46fbcf3.ttf: Connection reset by peer
flutter: If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to load font with url https://fonts.gstatic.com/s/a/d1adf80c80c93bbc514bb2899b3f84e2ff256004e9ad48bc405b568dc46fbcf3.ttf: Connection reset by peer
#0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:256:5)
<asynchronous suspension>
#1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:173:11)
<asynchronous suspension>
```

**Comment by guidezpl** [comment]
Without any additional information, I'm afraid no one can help with this issue. Please see #560 for troubleshooting
