### ISSUE TITLE
not load this fonts

### ISSUE THREAD

**Issue by deepak-9756** [material-foundation/flutter-packages#615]
### Package

All packages

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Steps to reproduce:
1.
1.
1.
not load fonts in my code

### Relevant log output

```shell
----------------FIREBASE CRASHLYTICS----------------
I/flutter (11931): Exception: Failed to load font with url https://fonts.gstatic.com/s/a/a05eb17c43309b14b916303c48995b19407a7cdcf47bc6d8085d464722627918.ttf: Failed host lookup: 'fonts.gstatic.com'
I/flutter (11931): 
I/flutter (11931): #0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:256:5)
I/flutter (11931): <asynchronous suspension>
I/flutter (11931): #1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:173:11)
I/flutter (11931): <asynchronous suspension>
I/flutter (11931): ----------------------------------------------------
I/flutter (11931): Error: google_fonts was unable to load font Poppins-SemiBold because the following exception occurred:
I/flutter (11931): Exception: Failed to load font with url https://fonts.gstatic.com/s/a/a24a61e9a408f85504dcdcd11edc4995adceb4ab585c0011f39cfbe193248b71.ttf: Failed host lookup: 'fonts.gstatic.com'
I/flutter (11931): 
I/flutter (11931): See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.
I/flutter (11931): If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
```

**Comment by JSBmanD** [comment]
I have the same problem, this don't doesn't load

**Comment by guidezpl** [comment]
Please see https://github.com/material-foundation/flutter-packages/issues/560 for troubleshooting steps
